import { Scene } from 'phaser';
import { resolvePublicAssetPath } from './AssetPath';

/**
 * Asset Intake System
 * 
 * Handles loading of placeholder assets generated by mmx CLI or manually dropped
 * into asset directories. Scans directories and auto-registers assets with Phaser
 * without requiring changes to battle code.
 */

export interface AssetManifest {
  tiles: string[];
  units: string[];
  markers: string[];
  ui: string[];
  effects: string[];
}

export class AssetIntake {
  private scene: Scene;
  private manifest: AssetManifest;
  private missingAssets: string[] = [];

  constructor(scene: Scene) {
    this.scene = scene;
    this.manifest = {
      tiles: ['tile-grass', 'tile-dirt', 'tile-stone', 'tile-water'],
      units: ['unit-vanguard', 'unit-skirmisher', 'unit-caster', 'unit-support', 'unit-controller'],
      markers: ['marker-extraction', 'marker-objective', 'marker-relic', 'marker-boss'],
      ui: ['ui-panel', 'ui-button', 'ui-cursor'],
      effects: ['effect-highlight', 'effect-path', 'effect-attack', 'effect-combo'],
    };
  }

  /**
   * Load all assets from the manifest
   * If an asset is missing, it will be tracked but not block loading
   */
  loadAllAssets(): void {
    this.missingAssets = [];

    // Load tile assets
    for (const key of this.manifest.tiles) {
      this.loadImage(key, `tiles/${key}.png`);
    }

    // Load unit assets
    for (const key of this.manifest.units) {
      this.loadImage(key, `units/${key}.png`);
    }

    // Load marker assets
    for (const key of this.manifest.markers) {
      this.loadImage(key, `markers/${key}.png`);
    }

    // Load UI assets
    for (const key of this.manifest.ui) {
      this.loadImage(key, `ui/${key}.png`);
    }

    // Load effect assets
    for (const key of this.manifest.effects) {
      this.loadImage(key, `effects/${key}.png`);
    }

    // Log missing assets for debugging
    if (this.missingAssets.length > 0) {
      console.warn('[AssetIntake] Missing assets:', this.missingAssets);
    }
  }

  /**
   * Load a single image asset with error handling
   */
  private loadImage(key: string, path: string): void {
    try {
      this.scene.load.image(key, resolvePublicAssetPath(path));
    } catch (error) {
      this.missingAssets.push(key);
      console.warn(`[AssetIntake] Failed to load ${key} from ${path}`);
    }
  }

  /**
   * Generate placeholder textures programmatically for missing assets
   * Call this in create() after load completes
   */
  generatePlaceholders(): void {
    const graphics = this.scene.add.graphics();

    // Generate tile placeholders
    for (const key of this.manifest.tiles) {
      if (!this.scene.textures.exists(key)) {
        this.generateTilePlaceholder(graphics, key);
      }
    }

    // Generate unit placeholders
    for (const key of this.manifest.units) {
      if (!this.scene.textures.exists(key)) {
        this.generateUnitPlaceholder(graphics, key);
      }
    }

    // Generate marker placeholders
    for (const key of this.manifest.markers) {
      if (!this.scene.textures.exists(key)) {
        this.generateMarkerPlaceholder(graphics, key);
      }
    }

    // Generate UI placeholders
    for (const key of this.manifest.ui) {
      if (!this.scene.textures.exists(key)) {
        this.generateUIPlaceholder(graphics, key);
      }
    }

    // Generate effect placeholders
    for (const key of this.manifest.effects) {
      if (!this.scene.textures.exists(key)) {
        this.generateEffectPlaceholder(graphics, key);
      }
    }

    graphics.destroy();
  }

  private generateTilePlaceholder(graphics: Phaser.GameObjects.Graphics, key: string): void {
    const colors: Record<string, number> = {
      'tile-grass': 0x4a7c59,
      'tile-dirt': 0x8b7355,
      'tile-stone': 0x7a7a7a,
      'tile-water': 0x4a90e2,
    };

    graphics.fillStyle(colors[key] || 0x888888, 1);
    graphics.fillRect(0, 0, 64, 64);
    graphics.lineStyle(2, 0x000000, 0.3);
    graphics.strokeRect(0, 0, 64, 64);
    
    graphics.generateTexture(key, 64, 64);
    graphics.clear();
  }

  private generateUnitPlaceholder(graphics: Phaser.GameObjects.Graphics, key: string): void {
    const colors: Record<string, number> = {
      'unit-vanguard': 0xcc4444,
      'unit-skirmisher': 0x44cc44,
      'unit-caster': 0x4444cc,
      'unit-support': 0xcccc44,
      'unit-controller': 0xcc44cc,
    };

    graphics.fillStyle(colors[key] || 0x888888, 1);
    graphics.fillCircle(24, 24, 20);
    graphics.lineStyle(3, 0xffffff, 1);
    graphics.strokeCircle(24, 24, 20);
    
    graphics.generateTexture(key, 48, 48);
    graphics.clear();
  }

  private generateMarkerPlaceholder(graphics: Phaser.GameObjects.Graphics, key: string): void {
    const colors: Record<string, number> = {
      'marker-extraction': 0x00ff00,
      'marker-objective': 0xffff00,
      'marker-relic': 0xffd700,
      'marker-boss': 0xff0000,
    };

    graphics.fillStyle(colors[key] || 0xffffff, 1);
    graphics.fillTriangle(16, 0, 32, 32, 0, 32);
    graphics.lineStyle(2, 0x000000, 0.5);
    graphics.strokeTriangle(16, 0, 32, 32, 0, 32);
    
    graphics.generateTexture(key, 32, 32);
    graphics.clear();
  }

  private generateUIPlaceholder(graphics: Phaser.GameObjects.Graphics, key: string): void {
    graphics.fillStyle(0x2a2a4a, 0.9);
    graphics.fillRect(0, 0, 200, 50);
    graphics.lineStyle(2, 0x4a4a8a, 1);
    graphics.strokeRect(0, 0, 200, 50);
    
    graphics.generateTexture(key, 200, 50);
    graphics.clear();
  }

  private generateEffectPlaceholder(graphics: Phaser.GameObjects.Graphics, key: string): void {
    const colors: Record<string, number> = {
      'effect-highlight': 0x00ff00,
      'effect-path': 0xffff00,
      'effect-attack': 0xff0000,
      'effect-combo': 0xff00ff,
    };

    graphics.fillStyle(colors[key] || 0xffffff, 0.5);
    graphics.fillCircle(16, 16, 14);
    
    graphics.generateTexture(key, 32, 32);
    graphics.clear();
  }

  /**
   * Check if all required assets are loaded
   */
  validateAssets(): boolean {
    const allAssets = [
      ...this.manifest.tiles,
      ...this.manifest.units,
      ...this.manifest.markers,
      ...this.manifest.ui,
      ...this.manifest.effects,
    ];

    const missing = allAssets.filter(key => !this.scene.textures.exists(key));
    
    if (missing.length > 0) {
      console.warn('[AssetIntake] Missing textures:', missing);
      return false;
    }

    return true;
  }

  /**
   * Get list of missing assets
   */
  getMissingAssets(): string[] {
    return [...this.missingAssets];
  }
}
